/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "lg:col-span-1",
    "lg:col-span-2",
    "lg:col-span-3",
    "lg:col-span-4",
    "lg:col-span-5",
    "lg:col-span-6",

    "bg-slate-400",
    "bg-gray-400",
    "bg-zinc-400",
    "bg-neutral-400",
    "bg-stone-400",
    "bg-red-400",
    "bg-orange-400",
    "bg-amber-400",
    "bg-yellow-400",
    "bg-lime-400",
    "bg-green-400",
    "bg-emerald-400",
    "bg-teal-400",
    "bg-cyan-400",
    "bg-sky-400",
    "bg-blue-400",
    "bg-indigo-400",
    "bg-violet-400",
    "bg-purple-400",
    "bg-fuchsia-400",
    "bg-pink-400",
    "bg-rose-400",

    "dark:bg-slate-700",
    "dark:bg-gray-700",
    "dark:bg-zinc-700",
    "dark:bg-neutral-700",
    "dark:bg-stone-700",
    "dark:bg-red-700",
    "dark:bg-orange-700",
    "dark:bg-amber-700",
    "dark:bg-yellow-700",
    "dark:bg-lime-700",
    "dark:bg-green-700",
    "dark:bg-emerald-700",
    "dark:bg-teal-700",
    "dark:bg-cyan-700",
    "dark:bg-sky-700",
    "dark:bg-blue-700",
    "dark:bg-indigo-700",
    "dark:bg-violet-700",
    "dark:bg-purple-700",
    "dark:bg-fuchsia-700",
    "dark:bg-pink-700",
    "dark:bg-rose-700",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
